// <auto-generated />
namespace SetSail.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nulle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nulle));
        
        string IMigrationMetadata.Id
        {
            get { return "202011081605318_nulle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
